version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/springboot-API
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "~/springboot-API/springboot-actuator/pom.xml" }}
        - v1-dependencies-
    - run: mvn -f ~/springboot-API/springboot-actuator/pom.xml dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "~/springboot-API/springboot-actuator/pom.xml" }}
    - run: mvn -f ~/springboot-API/springboot-actuator/pom.xml clean install
  deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/springboot-API
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "~/springboot-API/springboot-actuator/pom.xml" }}
        - v1-dependencies-
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "~/springboot-API/springboot-actuator/pom.xml"}}
    #- run: git subtree --prefix springboot-actuator push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build: 
    - deploy:
        requires:
        - build